<?php

    // First we execute our common code to connection to the database and start the session
require("common.php");

    // At the top of the page we check to see whether the user is logged in or not
if(empty($_SESSION['user']))
{
        // If they are not, we redirect them to the login page.
  header("Location: login.php");
  
        // Remember that this die statement is absolutely critical.  Without it,
        // people can view your members-only content without logging in.
  die("Redirecting to login.php");
}

    // Everything below this point in the file is secured by the login system

    // We can display the user's username to them by reading it from the session array.  Remember that because
    // a username is user submitted content we must use htmlentities on it before displaying it to the user.
?>
Hello <?php echo htmlentities($_SESSION['user']['username'], ENT_QUOTES, 'UTF-8'); ?>, secret content!<br />
and  <?php echo htmlentities($_SESSION['user']['skypeid'], ENT_QUOTES, 'UTF-8'); ?>, is your Skype ID!<br />
and  <?php echo htmlentities($_SESSION['user']['email'], ENT_QUOTES, 'UTF-8'); ?>, is your e-mail id!<br />
<a href="memberlist.php">Memberlist</a><br />
<a href="edit_account.php">Edit Account</a><br />
<a href="logout.php">Logout</a>

<?php
include_once "FirebaseToken.php";
$secret = "ZO1GLnFkLV23FJR5CsIhN2TzzpW2205mUmIuMWhP";
$tokenGen = new Services_FirebaseTokenGenerator($secret);
$userkaname= htmlentities($_SESSION['user']['username'], ENT_QUOTES, 'UTF-8');
$token = $tokenGen->createToken(array("id" => $userkaname , "isModerator" => true));
  //$token = $tokenGen->createToken(null, array("admin" => true, "debug" => true));

  //echo $token;
  // Get data only readable by auth.id = "example".
  //$uri = "https://zonker-firebase.firebaseio.com/.json?auth=".$token;
  //var_dump(file_get_contents($uri));
//echo $token;
?>

<!doctype html>
<html>
<head>
 <script type="text/javascript" src="http://cdn.dev.skype.com/uri/skype-uri.js"></script>
  <meta charset="utf-8" />
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <script src="https://cdn.firebase.com/v0/firebase-simple-login.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>

  <!-- Download from https://github.com/firebase/Firechat -->

  <!-- ../build refers to location of css and js generated by grunt => author: zonker -->
  <link rel="stylesheet" href="../build/firechat-default.min.css" />
  <script src="../build/firechat-default.min.js"></script>
  <style>
  #firechat-wrapper {
    height: 475px;
    max-width: 325px;
    padding: 10px;
    border: 1px solid #ccc;
    background-color: #fff;
    margin: 0px ;
    text-align: center;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    -webkit-box-shadow: 0 5px 25px #666;
    -moz-box-shadow: 0 5px 25px #666;
    box-shadow: 0 5px 25px #666;
  }
  </style>
</head>

<!--
  Example: Anonymous Authentication

  This example uses Firebase Simple Login to create 'anonymous' user sessions in Firebase,
  meaning that user credentials are not required, though a user has a valid Firebase
  authentication token and security rules still apply.

  Requirements: in order to use this example with your own Firebase, you'll need to do the following:
    1. Apply the security rules at https://github.com/firebase/firechat/blob/master/rules.json
    2. Enable the 'Anonymous' authentication provider in Forge
    3. Update the URL below to reference your Firebase
    4. Update the room id for auto-entry with a public room you have created
  -->
  <body>

    <script src="https://apis.google.com/js/platform.js"></script>
    <div id="placeholder-rr"></div>
    <script>
    gapi.hangout.render('placeholder-rr', {
      'render': 'createhangout',
      'initial_apps': [{'app_id' : '184219133185', 'start_data' : 'dQw4w9WgXcQ', 'app_type' : 'ROOM_APP' }],
      'widget_size': 175
    });

    </script>
    
    <div id="genSkypeCall">
      <script type="text/javascript">
      Skype.ui({
        name: "call",
        element: "genSkypeCall",
        participants: ["akhil.jindal12"],
        listParticipants: "true"
      });
      </script>
    </div>

    <div id="firechat-wrapper"></div>
    <br/>
    <script type='text/javascript'>
    var chatRef = new Firebase("https://zonker-firebase.firebaseio.com/");

    // Log me in.
    var php_token = "<?php echo $token; ?>"; //document.write(php_token);
    var chat = new FirechatUI(chatRef, document.getElementById("firechat-wrapper"));
    chatRef.auth(php_token, function(error,user) {    <!-- replacing AUTH_TOKEN by php_var -->
      if(error) {
        console.log("Login Failed!", error);
      }
      else if(user){
        console.log(user);
        console.log(user.id);

      }
      else {
        console.log("Login Succeeded!");
      }
    });
    chat.setUser("<?php echo htmlentities($_SESSION['user']['username'], ENT_QUOTES, 'UTF-8'); ?>", "<?php echo htmlentities($_SESSION['user']['username'], ENT_QUOTES, 'UTF-8'); ?>");
    setTimeout(function() {
      chat._chat.enterRoom('-Iy1N3xs4kN8iALHV0QA');
    }, 500);

    //console.log("Auth_ID ",auth.id);

    
    document.write("\nHello\n");
    document.write("\nthere!!\n");
    </script>


  </body>
  </html>